### ISSUE TITLE
Please solve this TypeError

### ISSUE THREAD

**Issue by UsarthiAruna** [parvatijay2901/Automatic-Number-plate-detection-for-Indian-vehicles#5]
Traceback (most recent call last):
  File "c:\anpr\Automatic-Number-plate-detection-for-Indian-vehicles-main\Program.py", line 154, in <module>
    res2 = str("".join(re.split("[^a-zA-Z0-9]*",number_plate)))
  File "C:\Python310\lib\re.py", line 230, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

**Comment by parvatijay2901** [comment]
check https://github.com/parvatijay2901/Automatic-Number-plate-detection-for-Indian-vehicles/issues/2#issuecomment-793467531
